---
# Per environment values which override defaults in hmpps-micro-frontend-poc-component/values.yaml

generic-service:
  replicaCount: 2

  env:
    INGRESS_URL: "https://micro-frontend-poc-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

